name: "{{.BotName}}"
description: My Awesome Discord (Dart) Bot
version: 0.1.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  botway_dart: ^0.1.0
  nyxx: ^3.4.2
  nyxx_commander: ^3.0.0
  nyxx_extensions: ^3.0.0
  nyxx_interactions: ^4.2.1
  nyxx_lavalink: ^3.0.1
  nyxx_pagination: ^2.2.0
